platform :ios, '8.0'
use_frameworks!

target 'kushki-ios_Example' do
  # Uncomment this line and comment the next one in order to use the library from CocoaPods instead
#   pod 'Kushki', '~> 2.0'
   pod 'Kushki', :path => '../'
  target 'kushki-ios_Tests' do
    inherit! :search_paths
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
